<a href="https://colab.research.google.com/github/kikiru328/enterprise_analysis/blob/main/Ranking.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# colab drive mount

import os, sys
from google.colab import drive
drive.mount('/content/drive')
my_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', my_path)
sys.path.insert(0,my_path)

Mounted at /content/drive

In [1]:

# Directory 변경 (모듈이용)
%pwd
%cd '../content/notebooks'
# module import
## Data Load
from pickle5 import pickle 

## Basic module
import pandas as pd
import numpy as np
import datetime as dt

/content/drive/My Drive/Colab Notebooks

In [22]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/기존_purprd_cust.pkl','rb') as file:
  df = pickle.load(file)

In [23]:
df_1 = df[(df['구매년도']==2014)&(df['구매월']>=1) & (df['구매월']<=6)] 
df_2= df[(df['구매년도']==2014)&(df['구매월']>=7) & (df['구매월']<=12)]
df_3= df[(df['구매년도']==2015)&(df['구매월']>=1) & (df['구매월']<=6)]
df_4 = df[(df['구매년도']==2015)&(df['구매월']>=7) & (df['구매월']<=12)]

In [26]:
t = pd.get_dummies(df_1['대분류명'])
t

          가공식품  가구/인테리어  교육/문화용품  기타  디지털/가전  ...  신선식품  의류  일상용품  전문스포츠/레저  패션잡화
14           1        0        0   0       0  ...     0   0     0         0     0
15           0        0        0   0       0  ...     1   0     0         0     0
16           0        0        0   0       0  ...     1   0     0         0     0
17           0        0        0   0       0  ...     1   0     0         0     0
18           0        0        0   0       0  ...     1   0     0         0     0
...        ...      ...      ...  ..     ...  ...   ...  ..   ...       ...   ...
28522872     1        0        0   0       0  ...     0   0     0         0     0
28522873     1        0        0   0       0  ...     0   0     0         0     0
28522874     1        0        0   0       0  ...     0   0     0         0     0
28522875     0        0        0   0       0  ...     0   0     1         0     0
28522876     1        0        0   0       0  ...     0   0     0         0     0

[6704092 rows x 11 columns]

In [32]:
Li = ['가공식품', '가구/인테리어', '교육/문화용품', '기타', '디지털/가전', '명품', '신선식품', '의류',
       '일상용품', '전문스포츠/레저', '패션잡화']

In [33]:
def ratio(df):
  test = df[['고객번호','대분류명']]
  test = test.set_index('고객번호')
  A = pd.get_dummies(test['대분류명']).reset_index()
  A = A.groupby('고객번호').sum().astype(int)
  A['total'] = A.sum(axis=1).astype(int)
  for i in Li:
    A[f"{i}_r"] = A[i] / A['total']
  B = A.drop(['가공식품', '가구/인테리어', '교육/문화용품', '기타', '디지털/가전', '명품', '신선식품', '의류',
    '일상용품', '전문스포츠/레저', '패션잡화','total'],axis=1)
  B['total'] = B.sum(axis=1)
  return B

In [34]:
H1_r = ratio(df_1)
H2_r = ratio(df_2)
H3_r = ratio(df_3)
H4_r = ratio(df_4)

In [44]:
a = H1_r.copy()

In [45]:
a_li = list(a.columns)
a_li

['가공식품_r',
 '가구/인테리어_r',
 '교육/문화용품_r',
 '기타_r',
 '디지털/가전_r',
 '명품_r',
 '신선식품_r',
 '의류_r',
 '일상용품_r',
 '전문스포츠/레저_r',
 '패션잡화_r',
 'total']

In [65]:
def reName(string,df):
  namelist = list(df.columns)
  for name in namelist:
    df = df.rename(columns={name:f'{string}_{name}'})
  return df

In [85]:
h1 = reName('H1',H1_r)
h2 = reName('H2',H2_r)
h3 = reName('H3',H3_r)
h4 = reName('H4',H4_r)

In [86]:
Test = pd.merge(h1,h2,on='고객번호',how='left')

In [89]:
Test = pd.merge(Test,h3,on='고객번호',how='left')

In [90]:
finaltest = pd.merge(Test,h4,on='고객번호',how='left')

In [91]:
finaltest.columns

Index(['H1_가공식품_r', 'H1_가구/인테리어_r', 'H1_교육/문화용품_r', 'H1_기타_r', 'H1_디지털/가전_r',
       'H1_명품_r', 'H1_신선식품_r', 'H1_의류_r', 'H1_일상용품_r', 'H1_전문스포츠/레저_r',
       'H1_패션잡화_r', 'H1_total', 'H2_가공식품_r', 'H2_가구/인테리어_r', 'H2_교육/문화용품_r',
       'H2_기타_r', 'H2_디지털/가전_r', 'H2_명품_r', 'H2_신선식품_r', 'H2_의류_r',
       'H2_일상용품_r', 'H2_전문스포츠/레저_r', 'H2_패션잡화_r', 'H2_total', 'H3_가공식품_r',
       'H3_가구/인테리어_r', 'H3_교육/문화용품_r', 'H3_기타_r', 'H3_디지털/가전_r', 'H3_명품_r',
       'H3_신선식품_r', 'H3_의류_r', 'H3_일상용품_r', 'H3_전문스포츠/레저_r', 'H3_패션잡화_r',
       'H3_total', 'H4_가공식품_r', 'H4_가구/인테리어_r', 'H4_교육/문화용품_r', 'H4_기타_r',
       'H4_디지털/가전_r', 'H4_명품_r', 'H4_신선식품_r', 'H4_의류_r', 'H4_일상용품_r',
       'H4_전문스포츠/레저_r', 'H4_패션잡화_r', 'H4_total'],
      dtype='object')

In [93]:
finaltest

       H1_가공식품_r  H1_가구/인테리어_r  ...  H4_패션잡화_r  H4_total
고객번호                            ...
1       0.277311      0.037815  ...   0.052980       1.0
2       0.141593      0.091445  ...   0.048980       1.0
3       0.681034      0.000000  ...   0.000000       1.0
4       0.333333      0.025926  ...   0.017778       1.0
5       0.320955      0.074271  ...   0.011236       1.0
...          ...           ...  ...        ...       ...
19356   0.617021      0.000000  ...   0.000000       1.0
19357   0.583333      0.000000  ...   0.005848       1.0
19359   0.647059      0.000000  ...   0.000000       1.0
19360   0.487805      0.000000  ...   0.012500       1.0
19364   0.095745      0.000000  ...   0.000000       1.0

[19085 rows x 48 columns]

In [94]:
finaltest.columns

Index(['H1_가공식품_r', 'H1_가구/인테리어_r', 'H1_교육/문화용품_r', 'H1_기타_r', 'H1_디지털/가전_r',
       'H1_명품_r', 'H1_신선식품_r', 'H1_의류_r', 'H1_일상용품_r', 'H1_전문스포츠/레저_r',
       'H1_패션잡화_r', 'H1_total', 'H2_가공식품_r', 'H2_가구/인테리어_r', 'H2_교육/문화용품_r',
       'H2_기타_r', 'H2_디지털/가전_r', 'H2_명품_r', 'H2_신선식품_r', 'H2_의류_r',
       'H2_일상용품_r', 'H2_전문스포츠/레저_r', 'H2_패션잡화_r', 'H2_total', 'H3_가공식품_r',
       'H3_가구/인테리어_r', 'H3_교육/문화용품_r', 'H3_기타_r', 'H3_디지털/가전_r', 'H3_명품_r',
       'H3_신선식품_r', 'H3_의류_r', 'H3_일상용품_r', 'H3_전문스포츠/레저_r', 'H3_패션잡화_r',
       'H3_total', 'H4_가공식품_r', 'H4_가구/인테리어_r', 'H4_교육/문화용품_r', 'H4_기타_r',
       'H4_디지털/가전_r', 'H4_명품_r', 'H4_신선식품_r', 'H4_의류_r', 'H4_일상용품_r',
       'H4_전문스포츠/레저_r', 'H4_패션잡화_r', 'H4_total'],
      dtype='object')

In [100]:
with open ('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/매출감소고객_예측모델_변수생성/모든반기_변수모음/4반기_변수모음/Half_4_prod_ratio.pkl','wb') as save:
  pickle.dump(h4,save)

In [101]:
a_li

['가공식품_r',
 '가구/인테리어_r',
 '교육/문화용품_r',
 '기타_r',
 '디지털/가전_r',
 '명품_r',
 '신선식품_r',
 '의류_r',
 '일상용품_r',
 '전문스포츠/레저_r',
 '패션잡화_r',
 'total']

In [112]:
trainlist = ['H1','H2','H3']

In [119]:
trainList = []
for col in a_li:
  for h in trainlist:
    trainList.append(f'{h}_{col}')

In [120]:
trainList

['H1_가공식품_r',
 'H2_가공식품_r',
 'H3_가공식품_r',
 'H1_가구/인테리어_r',
 'H2_가구/인테리어_r',
 'H3_가구/인테리어_r',
 'H1_교육/문화용품_r',
 'H2_교육/문화용품_r',
 'H3_교육/문화용품_r',
 'H1_기타_r',
 'H2_기타_r',
 'H3_기타_r',
 'H1_디지털/가전_r',
 'H2_디지털/가전_r',
 'H3_디지털/가전_r',
 'H1_명품_r',
 'H2_명품_r',
 'H3_명품_r',
 'H1_신선식품_r',
 'H2_신선식품_r',
 'H3_신선식품_r',
 'H1_의류_r',
 'H2_의류_r',
 'H3_의류_r',
 'H1_일상용품_r',
 'H2_일상용품_r',
 'H3_일상용품_r',
 'H1_전문스포츠/레저_r',
 'H2_전문스포츠/레저_r',
 'H3_전문스포츠/레저_r',
 'H1_패션잡화_r',
 'H2_패션잡화_r',
 'H3_패션잡화_r',
 'H1_total',
 'H2_total',
 'H3_total']

In [123]:
finaltest = finaltest[trainList]

In [125]:
with open ('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/매출감소고객_예측모델_변수생성/모든반기_변수모음/123반기_변수모음/Half_123_prod_ratio.pkl','wb') as save:
  pickle.dump(finaltest,save)

In [44]:
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/pr_1','rb') as f1:
  pr_1 = pickle.load(f1)
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/pr_2','rb') as f2:
  pr_2 = pickle.load(f2)
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/pr_3','rb') as f3:
  pr_3 = pickle.load(f3)
with open('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/data/EDA/pr_4','rb') as f4:
  pr_4 = pickle.load(f4)

In [45]:
def Makingstandard(df):
  df = df.reset_index(drop=False)
  df = df.rename(columns={'index':'고객번호'})
  df = df.set_index('고객번호',drop=True)
  return df

pr_1 = Makingstandard(pr_1)
pr_2 = Makingstandard(pr_2)
pr_3 = Makingstandard(pr_3)
pr_4 = Makingstandard(pr_4)

In [46]:
sorting_cols = ['가공식품_구매금액',
 '가구/인테리어_구매금액',
 '교육/문화용품_구매금액',
 '기타_구매금액',
 '디지털/가전_구매금액',
 '명품_구매금액',
 '신선식품_구매금액',
 '의류_구매금액',
 '일상용품_구매금액',
 '전문스포츠/레저_구매금액',
 '패션잡화_구매금액',
 '총구매금액']

def_cols = ['가공식품_구매금액','가구/인테리어_구매금액',
 '교육/문화용품_구매금액',
 '기타_구매금액',
 '디지털/가전_구매금액',
 '명품_구매금액',
 '신선식품_구매금액',
 '의류_구매금액',
 '일상용품_구매금액',
 '전문스포츠/레저_구매금액',
 '패션잡화_구매금액']
 
sum_cols = ['가공식품_구매금액_r', 
'가구/인테리어_구매금액_r', 
'교육/문화용품_구매금액_r',
'기타_구매금액_r',
'디지털/가전_구매금액_r',
'명품_구매금액_r',
'신선식품_구매금액_r',
'의류_구매금액_r',
'일상용품_구매금액_r',
'전문스포츠/레저_구매금액_r',
'패션잡화_구매금액_r']

confirm_cols = ['가공식품_구매금액_r',
'가구/인테리어_구매금액_r',
'교육/문화용품_구매금액_r',
'기타_구매금액_r',
'디지털/가전_구매금액_r',
'명품_구매금액_r',
'신선식품_구매금액_r',
'의류_구매금액_r',
'일상용품_구매금액_r',
'전문스포츠/레저_구매금액_r',
'패션잡화_구매금액_r',
'total']

In [47]:
pr_1 = pr_1[sorting_cols]
pr_2 = pr_2[sorting_cols]
pr_3 = pr_3[sorting_cols]
pr_4 = pr_4[sorting_cols]

In [49]:
def ratio(df):
  global sorting_cols, def_cols, sum_cols, confirm_cols
  s_df = df[sorting_cols]
  for i in def_cols:
    s_df[f'{i}_r'] = s_df[i] / s_df['총구매금액']
  s_df['total'] = s_df[sum_cols].sum(axis=1)
  s_df = s_df[confirm_cols]
  return s_df

In [50]:
pp_1 = ratio(pr_1)
pp_2 = ratio(pr_2)
pp_3 = ratio(pr_3)
pp_4 = ratio(pr_4)

In [51]:
pp_1

       가공식품_구매금액_r  가구/인테리어_구매금액_r  ...  패션잡화_구매금액_r  total
고객번호                                ...
1         0.178166        0.034956  ...     0.086165    1.0
2         0.061068        0.071338  ...     0.037138    1.0
3         0.622933        0.000000  ...     0.000000    1.0
4         0.160786        0.024942  ...     0.153065    1.0
5         0.242790        0.076066  ...     0.040030    1.0
...            ...             ...  ...          ...    ...
19356     0.515221        0.000000  ...     0.000000    1.0
19357     0.322458        0.000000  ...     0.000000    1.0
19359     0.284788        0.000000  ...     0.000000    1.0
19360     0.227551        0.000000  ...     0.000000    1.0
19364     0.028833        0.000000  ...     0.000000    1.0

[19085 rows x 12 columns]

In [52]:
def reName(string,df):
  namelist = list(df.columns)
  for name in namelist:
    df = df.rename(columns={name:f'{string}_{name}'})
  return df

In [53]:
h1 = reName('H1',pp_1)
h2 = reName('H2',pp_2)
h3 = reName('H3',pp_3)
h4 = reName('H4',pp_4)

In [65]:
with open ('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/매출감소고객_예측모델_변수생성/모든반기_변수모음/123반기_변수모음/Half_3_amount_ratio.pkl', 'wb') as save:
  pickle.dump(h3,save)

In [66]:
with open ('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/매출감소고객_예측모델_변수생성/모든반기_변수모음/4반기_변수모음/Half_4_amount_ratio.pkl', 'wb') as save:
  pickle.dump(h4,save)

In [56]:
Test = pd.merge(h1,h2,on='고객번호',how='left')
Test_2 = pd.merge(Test,h3,on='고객번호',how='left')
finaltest = pd.merge(Test_2,h4,on='고객번호',how='left')
finaltest

       H1_가공식품_구매금액_r  H1_가구/인테리어_구매금액_r  ...  H4_패션잡화_구매금액_r  H4_total
고객번호                                      ...
1            0.178166           0.034956  ...        0.079683       1.0
2            0.061068           0.071338  ...        0.038138       1.0
3            0.622933           0.000000  ...        0.000000       1.0
4            0.160786           0.024942  ...        0.068232       1.0
5            0.242790           0.076066  ...        0.003822       1.0
...               ...                ...  ...             ...       ...
19356        0.515221           0.000000  ...        0.000000       1.0
19357        0.322458           0.000000  ...        0.080118       1.0
19359        0.284788           0.000000  ...        0.000000       1.0
19360        0.227551           0.000000  ...        0.242647       1.0
19364        0.028833           0.000000  ...        0.000000       1.0

[19085 rows x 48 columns]

In [59]:
a_list = list(pp_1.columns)

In [57]:
trainlist = ['H1','H2','H3']

In [61]:
trainList = []
for col in a_list:
  for h in trainlist:
    trainList.append(f'{h}_{col}')
trainList

['H1_가공식품_구매금액_r',
 'H2_가공식품_구매금액_r',
 'H3_가공식품_구매금액_r',
 'H1_가구/인테리어_구매금액_r',
 'H2_가구/인테리어_구매금액_r',
 'H3_가구/인테리어_구매금액_r',
 'H1_교육/문화용품_구매금액_r',
 'H2_교육/문화용품_구매금액_r',
 'H3_교육/문화용품_구매금액_r',
 'H1_기타_구매금액_r',
 'H2_기타_구매금액_r',
 'H3_기타_구매금액_r',
 'H1_디지털/가전_구매금액_r',
 'H2_디지털/가전_구매금액_r',
 'H3_디지털/가전_구매금액_r',
 'H1_명품_구매금액_r',
 'H2_명품_구매금액_r',
 'H3_명품_구매금액_r',
 'H1_신선식품_구매금액_r',
 'H2_신선식품_구매금액_r',
 'H3_신선식품_구매금액_r',
 'H1_의류_구매금액_r',
 'H2_의류_구매금액_r',
 'H3_의류_구매금액_r',
 'H1_일상용품_구매금액_r',
 'H2_일상용품_구매금액_r',
 'H3_일상용품_구매금액_r',
 'H1_전문스포츠/레저_구매금액_r',
 'H2_전문스포츠/레저_구매금액_r',
 'H3_전문스포츠/레저_구매금액_r',
 'H1_패션잡화_구매금액_r',
 'H2_패션잡화_구매금액_r',
 'H3_패션잡화_구매금액_r',
 'H1_total',
 'H2_total',
 'H3_total']

In [62]:
train = finaltest[trainList]
train

       H1_가공식품_구매금액_r  H2_가공식품_구매금액_r  ...  H2_total  H3_total
고객번호                                   ...
1            0.178166        0.048131  ...       1.0       1.0
2            0.061068        0.055223  ...       1.0       1.0
3            0.622933        0.548384  ...       1.0       1.0
4            0.160786        0.121463  ...       1.0       1.0
5            0.242790        0.312706  ...       1.0       1.0
...               ...             ...  ...       ...       ...
19356        0.515221        0.538920  ...       1.0       1.0
19357        0.322458        0.431969  ...       1.0       1.0
19359        0.284788        0.615100  ...       1.0       1.0
19360        0.227551        0.204647  ...       1.0       1.0
19364        0.028833        0.032158  ...       1.0       1.0

[19085 rows x 36 columns]

In [67]:
with open ('/content/drive/MyDrive/공유문서/1차 프로젝트/5조/매출감소고객_예측모델_변수생성/모든반기_변수모음/123반기_변수모음/Half_123_amount_ratio.pkl', 'wb') as save:
  pickle.dump(train,save)