In [ ]:
# 나눔 폰트 설치
!sudo apt-get install -y fonts-nanum
!sudo fc-cashe -fv
!rm ~/.cache/matplotlib -rf
# 순서 : 마운트초기화 > 폰트설치 > 런타임다시시작 > 구글드라이브 마운트 > 나머지 코드...

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  fonts-nanum
0 upgraded, 1 newly installed, 0 to remove and 37 not upgraded.
Need to get 9,604 kB of archives.
After this operation, 29.5 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/universe amd64 fonts-nanum all 20170925-1 [9,604 kB]
Fetched 9,604 kB in 1s (6,655 kB/s)
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76, <> line 1.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
Selecting previously unselected package fonts-nanum.
(Reading database ... 155047 files and directories currently installed.)
Preparing to unpack .../fonts-nanum_20170925-1_all.deb ...
Unpacking fonts-nanum (20170925-1) ...
Setting up fonts-nanum (20170925-1) ...
Processing triggers for fontconfig (2.12.6-0ubuntu2) ...
sudo: fc-cashe: command not found

In [ ]:
import matplotlib.pyplot as plt
plt.rc('font', family='NanumBarunGothic')

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime
import warnings
warnings.filterwarnings('ignore')

In [ ]:
import os, sys
from google.colab import drive
drive.mount('/content/drive')
my_path = '/content/notebooks'
os.symlink('/content/drive/My Drive/Colab Notebooks', my_path)
sys.path.insert(0,my_path)

Mounted at /content/drive

In [ ]:
import pickle
with open("/content/drive/MyDrive/cakd3_1차프로젝트_2조/dataset/Ldata0920.pkl", "rb") as fh: Ldata = pickle.load(fh)

In [ ]:
data = Ldata['구매상품']
data

         제휴사    영수증번호  대분류코드  중분류코드  ...   거주지역     분류 체계    중분류명    소분류명
0          B  8664000     15   1504  ...  100.0        식품    탄산음료     사이다
1          B  8747265     15   1504  ...  100.0        식품    탄산음료     사이다
2          B  8720725     15   1504  ...  100.0        식품    탄산음료     사이다
3          B  8725005     15   1504  ...  100.0        식품    탄산음료     사이다
4          B  8748478     15   1504  ...  100.0        식품    탄산음료     사이다
...       ..      ...    ...    ...  ...    ...       ...     ...     ...
28593025   C  1073027      3    303  ...  540.0        식품     근채류  기타한방약재
28593026   C  8635424     17   1701  ...  100.0      일상용품    주방용품   보온도시락
28593027   C   985626     17   1702  ...  500.0      일상용품  청소욕실용품  욕실수납용품
28593028   C  7570422     17   1705  ...  570.0  전문스포츠/레저    레저취미  기타탁구용품
28593029   C  7335442     17   1703  ...  310.0        가전    전기전자  핸디형청소기

[28593030 rows x 21 columns]

In [ ]:
년도14 = data.query('년==2014').groupby('분류 체계')['구매금액'].sum().sort_values(ascending=False).to_frame()
년도15 = data.query('년==2015').groupby('분류 체계')['구매금액'].sum().sort_values(ascending=False).to_frame()
년도14.rename(columns={'구매금액':'2014_구매금액'}, inplace=True)
년도15.rename(columns={'구매금액':'2015_구매금액'}, inplace=True)

procat = pd.concat([년도14, 년도15], axis=1)
procat

            2014_구매금액     2015_구매금액
분류 체계
의류        98774369138  104572514708
식품        75980019796   77990857279
패션잡화      40076885270   43715298795
일상용품      36424991514   38021332954
기타        27336430728   31003769044
전문스포츠/레저  24781697410   22829647676
가전        13498000990   15844790725
가구/인테리어   10176481673   11067355775
교육/문화용품    1946968001    1732789654
의약품         605996061     638959750

In [ ]:
증감 = 년도15['2015_구매금액']/년도14['2014_구매금액'] * 100 - 100
증감 = (년도15['2015_구매금액'] - 년도14['2014_구매금액'])/년도14['2014_구매금액'] *100
증감 = 증감.to_frame()
증감.rename(columns={0 : '증감%'}, inplace=True)
증감

                증감%
분류 체계
의류         5.870091
식품         2.646535
패션잡화       9.078584
일상용품       4.382544
기타        13.415571
전문스포츠/레저  -7.876982
가전        17.386202
가구/인테리어    8.754245
교육/문화용품  -11.000610
의약품        5.439588

In [ ]:
procat = pd.concat([procat, 증감], axis=True)
procat

            2014_구매금액     2015_구매금액        증감%
분류 체계
의류        98774369138  104572514708   5.870091
식품        75980019796   77990857279   2.646535
패션잡화      40076885270   43715298795   9.078584
일상용품      36424991514   38021332954   4.382544
기타        27336430728   31003769044  13.415571
전문스포츠/레저  24781697410   22829647676  -7.876982
가전        13498000990   15844790725  17.386202
가구/인테리어   10176481673   11067355775   8.754245
교육/문화용품    1946968001    1732789654 -11.000610
의약품         605996061     638959750   5.439588

## **반기별/품목별 증감액**

In [ ]:
반기14_1 = data.query('년==2014&분기==1|분기==2').groupby('분류 체계')['구매금액'].sum().to_frame()
반기14_2 = data.query('년==2014&분기==3|분기==4').groupby('분류 체계')['구매금액'].sum().to_frame()
반기15_1 = data.query('년==2015&분기==1|분기==2').groupby('분류 체계')['구매금액'].sum().to_frame()
반기15_2 = data.query('년==2015&분기==3|분기==4').groupby('분류 체계')['구매금액'].sum().to_frame()


반기14_1.rename(columns={'구매금액':'2014_1분기_구매금액'}, inplace=True)
반기14_2.rename(columns={'구매금액':'2014_2분기_구매금액'}, inplace=True)
반기15_1.rename(columns={'구매금액':'2015_1분기_구매금액'}, inplace=True)
반기15_2.rename(columns={'구매금액':'2015_2분기_구매금액'}, inplace=True)

In [ ]:
반기2014_12 = pd.concat([반기14_1,반기14_2], axis=1)
반기2014_2_2015_1 = pd.concat([반기14_2,반기15_1], axis=1)
반기2015_12 = pd.concat([반기15_1,반기15_2], axis=1)

In [ ]:
증감_1 = (반기14_2['2014_2분기_구매금액'] - 반기14_1['2014_1분기_구매금액'])/반기14_1['2014_1분기_구매금액'] *100
증감_2 = (반기15_1['2015_1분기_구매금액'] - 반기14_2['2014_2분기_구매금액'])/반기14_2['2014_2분기_구매금액'] *100
증감_3 = (반기15_2['2015_2분기_구매금액'] - 반기15_1['2015_1분기_구매금액'])/반기15_1['2015_1분기_구매금액'] *100

증감_1 = 증감_1.to_frame()
증감_2 = 증감_2.to_frame()
증감_3 = 증감_3.to_frame()

증감_1.rename(columns={0 : '증감%_1'}, inplace=True)
증감_2.rename(columns={0 : '증감%_2'}, inplace=True)
증감_3.rename(columns={0 : '증감%_3'}, inplace=True)

In [ ]:
df1 = pd.concat([반기2014_12, 증감_1], axis=1)
df2 = pd.concat([반기2014_2_2015_1, 증감_2], axis=1)
df3 = pd.concat([반기2015_12, 증감_3], axis=1)

display(df1, df2, df3)

          2014_1분기_구매금액  2014_2분기_구매금액      증감%_1
분류 체계
가구/인테리어      7445004532     8757045191  17.623101
가전          10461730870    11597233160  10.853866
교육/문화용품      1377843648     1414655858   2.671726
기타          20195401493    23425109111  15.992292
식품          56036574554    56031212061  -0.009570
의류          71077629258    86204997450  21.282882
의약품           458610160      467173890   1.867322
일상용품        27297232922    28513782886   4.456679
전문스포츠/레저    18189508536    19913389774   9.477338
패션잡화        30535868357    33628126275  10.126642

          2014_2분기_구매금액  2015_1분기_구매금액      증감%_2
분류 체계
가구/인테리어      8757045191     7727109227 -11.761227
가전          11597233160    10516003270  -9.323171
교육/문화용품      1414655858     1353374022  -4.331925
기타          23425109111    21583073250  -7.863510
식품          56031212061    57387012863   2.419724
의류          86204997450    73010912231 -15.305476
의약품           467173890      476405870   1.976134
일상용품        28513782886    28037164688  -1.671536
전문스포츠/레저    19913389774    18055284030  -9.330936
패션잡화        33628126275    31688778091  -5.767042

          2015_1분기_구매금액  2015_2분기_구매금액      증감%_3
분류 체계
가구/인테리어      7727109227     8980396480  16.219355
가전          10516003270    12291246055  16.881345
교육/문화용품      1353374022     1282808586  -5.214038
기타          21583073250    24237230960  12.297404
식품          57387012863    57027544705  -0.626393
의류          73010912231    87687188920  20.101484
의약품           476405870      482573421   1.294600
일상용품        28037164688    28757676502   2.569845
전문스포츠/레저    18055284030    19418502276   7.550245
패션잡화        31688778091    34374394094   8.474975

## **2014년 상반기 대비 2015년 상반기 고객별 매출 증감 지수화**

In [ ]:
# df = data.groupby(['년','분기'])['구매금액'].agg(['sum', 'count'])
# df1 = df.reset_index(1).query('분기==1|분기==2')

# df1 = df1.reset_index()
# df1 = df1.groupby('년').sum()
# df1

      분기           sum    count
년
2014   3  158240730140  6709382
2015   3  169289150145  7474098

In [ ]:
# # 14상반기, 15 상반기 비교 --> 실패
# from sklearn.preprocessing import MinMaxScaler

# scaler = MinMaxScaler()

# data_scaled = scaler.fit_transform(df1)
# data_scaled

array([[0., 0., 0.],
       [0., 1., 1.]])

In [ ]:
df = data.groupby(['고객번호','년','분기'])['구매금액'].agg(['sum', 'count'])
df1 = df.reset_index(2).query('분기==1|분기==2')

df1 = df1.reset_index()
df1 = df1.groupby(['고객번호','년']).sum()
df1.reset_index()

        고객번호     년  분기       sum  count
0          1  2014   3  19925355    238
1          1  2015   3  17898365    312
2          2  2014   3  24323230    339
3          2  2015   3  27791610    261
4          3  2014   3    851215    348
...      ...   ...  ..       ...    ...
38548  19379  2015   3   2395920    262
38549  19380  2015   3    837950    103
38550  19381  2015   3   2797171    369
38551  19382  2015   3   1826739    398
38552  19383  2015   2     27000      5

[38553 rows x 5 columns]

In [ ]:
df1.reset_index(inplace=True)

In [ ]:
df2 = pd.pivot_table(df1,
               columns='년',
               index='고객번호',
               values='sum')

In [ ]:
df2.dropna(axis=0,inplace=True)
display(df2, df2.shape)

년            2014        2015
고객번호
1      19925355.0  17898365.0
2      24323230.0  27791610.0
3        851215.0    592280.0
4       5042106.0   3656937.0
5       5460150.0   2934930.0
...           ...         ...
19356    170160.0   2104968.0
19357     91950.0   3044944.0
19359     43190.0    837240.0
19360    368050.0   1412140.0
19364   2032420.0   3218130.0

[19183 rows x 2 columns]

(19183, 2)

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

df2_scaled = scaler.fit_transform(df2)
df2_scaled

array([[1.43423737e-02, 1.71206530e-02],
       [1.75085351e-02, 2.65852425e-02],
       [6.10331314e-04, 5.64407723e-04],
       ...,
       [2.86100115e-05, 7.98754072e-04],
       [2.62486417e-04, 1.34874475e-03],
       [1.46071603e-03, 3.07648464e-03]])

In [ ]:
df2_scaled = pd.DataFrame(df2_scaled, columns=['2014', '2015'])
df2_scaled

           2014      2015
0      0.014342  0.017121
1      0.017509  0.026585
2      0.000610  0.000564
3      0.003627  0.003496
4      0.003928  0.002806
...         ...       ...
19178  0.000120  0.002012
19179  0.000064  0.002911
19180  0.000029  0.000799
19181  0.000262  0.001349
19182  0.001461  0.003076

[19183 rows x 2 columns]